version: "2"

services:
  myapp:
    image: "docker.io/bitnami/symfony:1-debian-10"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=origami
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=myapp
    depends_on:
      - mariadb
  mariadb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=origami
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=myapp
